### ISSUE TITLE
[Enhancement]: MC 1.20.1 compatibility?

### ISSUE THREAD

**Issue by VewDev** [Craft1x/MultiRecipe#1]
I am currently hosting a "Chosen's Modded Adventure" server, which is in 1.20.1

Recently, one of my players reported to me a recipe issue with a "flint block".

I tried manually installing this mod in my client and forge tells me at least 1.20.2 is required.

Any chance the mod can be ported or enabled for 1.20.2?

**Comment by Craft1x** [comment]
Hi, for 1.20.1 version you should use polymorph: https://www.curseforge.com/minecraft/mc-mods/polymorph
